### PR TITLE
docs: added MongoDB 5.0 CPU/virtualization requirements note

### PR DESCRIPTION
**Pull request by viniarck**
### Summary

- Added MongoDB 5.0 CPU/virtualization requirements note.

It turns out that some students ended up hitting this issue when trying to contribute to Kytos-ng. Thanks, @Alopalao for helping out the students with this one. Hopefully now at least with this note here in the docs it'll make them aware of what needs to be done. In a newer docs we can also provide more information, in the meantime we can also link this current link below here that Aldo has shared.

References:

- https://forums.virtualbox.org/viewtopic.php?f=25&t=99390 (follow this tutorial to disable)
- https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-windows/ (MongoDB general notes about it)

### CODE REVIEW

**Comment by Alopalao** [comment]
LGTM. Could we add the intructions from VirtualBox to the document? Looks like there are more services that could be using Hyper-V and need to be disabled.

**Review by Alopalao — APPROVED** [review]
LGTM. Could we add the intructions from VirtualBox to the document? Looks like there are more services that could be using Hyper-V and need to be disabled.

**Comment by viniarck** [comment]
> LGTM. Could we add the intructions from VirtualBox to the document? Looks like there are more services that could be using Hyper-V and need to be disabled.

Sure. Let's try to summarize it. @Alopalao, let me know if this is sufficient below or if you'd like to include more info:

```
- Find the Command Prompt icon, right click it and choose Run As Administrator.
- Enter this command: `bcdedit /set hypervisorlaunchtype off`
- Some report this command was needed also: `DISM /Online /Disable-Feature:Microsoft-Hyper-V`
- Reboot
```

**Comment by Alopalao** [comment]
Reading more about it, those steps should be enough.

**Comment by viniarck** [comment]
> - Find the Command Prompt icon, right click it and choose Run As Administrator.
> - Enter this command: `bcdedit /set hypervisorlaunchtype off`
> - Some report this command was needed also: `DISM /Online /Disable-Feature:Microsoft-Hyper-V`
> - Reboot

Right. Done here https://github.com/kytos-ng/documentation/commit/f5e1d59ce3faf6e97f48b9a3f7bc7a4694df12dc

**Pull request merged**
